
set libdir $::env(libdir)
set incdir $::env(incdir)

set ::env(LD_LIBRARY_PATH) ${libdir}

### test the util.h header
# including the util header should not produce warnings
given the c code "
    #include <grapes/util.h>
    int main (void) { return 0; }"
  when I compile with cflags "-I${incdir} -Wall -Wextra"
  then I should not see "warning"
  and it should return 0

### test the compiletime static_assert macro
# compilation should fail if the condition is false
given the c code "
    #include <grapes/util.h>
    static_assert(0);
    int main (void) { return 0; }"
  when I compile with cflags "-I${incdir} -Wall -Wextra"
  then it should not return 0
# it should succeed if the given condition is true
given the c code "
    #include <grapes/util.h>
    static_assert(1);
    int main (void) { return 0; }"
  when I compile with cflags "-I${incdir} -Wall -Wextra"
  then it should return 0

### test the __precondition macro
# __precondition should succeed and not print if the condition is true
given the c code "
    #include <grapes/util.h>
    int main (void) {
      __returns_int;
      int some_variable = 1;
      __precondition(1 == some_variable);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    int main (void) {
      __returns_int;
      int some_variable = 1;
      __precondition(1 == some_variable);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    int main (void) {
      __returns_int;
      int some_variable = 0;
      __precondition(1 == some_variable);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    int main (void) {
      __returns_int;
      int some_variable = 0;
      __precondition(1 == some_variable);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:6: error: precondition failed: 1 == some_variable"
  and it should not return 0
# __precondition should behave the same in a function returning a pointer type
given the c code "
    #include <grapes/util.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 1;
      __precondition(1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 1;
      __precondition(1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 0;
      __precondition(1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 0;
      __precondition(1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:6: error: precondition failed: 1 == some_variable"
  and it should not return 0
# __precondition should allow to set errno
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int func(void) {
      __returns_int;
      int some_variable = 1;
      __precondition(ENOSYS, 1 == some_variable);
      return 0;
    }
    int main (void) {
      int res = func();
      perror(\"message\");
      if (res) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
  when I run
  then I should see "message: Success"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int func(void) {
      __returns_int;
      int some_variable = 1;
      __precondition(ENOSYS, 1 == some_variable);
      return 0;
    }
    int main (void) {
      int res = func();
      perror(\"message\");
      if (res) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
  when I run
  then I should see "message: Success"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int func(void) {
      __returns_int;
      int some_variable = 0;
      __precondition(ENOSYS, 1 == some_variable);
      return 0;
    }
    int main (void) {
      int res = func();
      perror(\"message\");
      if (res) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should not return 0
  when I run
  then I should see "message: Function not implemented"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int func(void) {
      __returns_int;
      int some_variable = 0;
      __precondition(ENOSYS, 1 == some_variable);
      return 0;
    }
    int main (void) {
      int res = func();
      perror(\"message\");
      if (res) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:7: error: precondition failed: 1 == some_variable"
  and I should see "message: Function not implemented"
  and it should not return 0
# the same shold happen in a function returning a pointer type
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 1;
      __precondition(ENOSYS, 1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      perror(\"message\");
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
  when I run
  then I should see "message: Success"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 1;
      __precondition(ENOSYS, 1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      perror(\"message\");
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should return 0
  when I run
  then I should see "message: Success"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 0;
      __precondition(ENOSYS, 1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      perror(\"message\");
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "some_variable"
  and it should not return 0
  when I run
  then I should see "message: Function not implemented"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    void *func(void) {
      __returns_ptr;
      int some_variable = 0;
      __precondition(ENOSYS, 1 == some_variable);
      return (void*)0x5;
    }
    int main (void) {
      void *p = func();
      perror(\"message\");
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:7: error: precondition failed: 1 == some_variable"
  and I should see "message: Function not implemented"
  and it should not return 0

### test the __checked_call macros
# __checked_call should behave like assert_inner with implicit message string
given the c code "
    #include <grapes/util.h>
    int func (void) { return 0; }
    int main (void) {
      __returns_int;
      __checked_call(0 == func());
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    int func (void) { return 0; }
    int main (void) {
      __returns_int;
      __checked_call(0 == func());
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    int func (void) { return 1; }
    int main (void) {
      __returns_int;
      __checked_call(0 == func());
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    int func (void) { return 1; }
    int main (void) {
      __returns_int;
      __checked_call(0 == func());
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:6: error: checked call failed: 0 == func()"
  and it should not return 0
# __checked_call_ptr should behave like assert_inner_ptr
given the c code "
    #include <grapes/util.h>
    int func (void) { return 0; }
    void *func1(void) {
      __returns_ptr;
      __checked_call(0 == func());
      return (void*)0x5;
    }
    int main (void) {
      void *p = func1();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should return 0
# the same thing should happen if DEBUG is set
given the c code "
    #include <grapes/util.h>
    int func (void) { return 0; }
    void *func1(void) {
      __returns_ptr;
      __checked_call(0 == func());
      return (void*)0x5;
    }
    int main (void) {
      void *p = func1();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should return 0
# it should fail and not print the message if the condition is false
given the c code "
    #include <grapes/util.h>
    int func (void) { return 1; }
    void *func1(void) {
      __returns_ptr;
      __checked_call(0 == func());
      return (void*)0x5;
    }
    int main (void) {
      void *p = func1();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should not return 0
# when DEBUG is set, the message should be seen
given the c code "
    #include <grapes/util.h>
    int func (void) { return 1; }
    void *func1(void) {
      __returns_ptr;
      __checked_call(0 == func());
      return (void*)0x5;
    }
    int main (void) {
      void *p = func1();
      if (!p) return 1;
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:6: error: checked call failed: 0 == func()"
  and it should not return 0
# __checked_call should accept a second parameter
  given the c code "
      #include <stdio.h>
      #include <grapes/util.h>
      int func (void) { return 0; }
      int main (void) {
        __returns_int;
        __checked_call(0 == func(),
          printf(\"executed\\n\");
        );
        return 0;
      }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should not see "func"
  and it should return 0
  when I run
  then I should not see "executed"
  and it should return 0
# it should execute the code block parameter on failure
  given the c code "
      #include <stdio.h>
      #include <grapes/util.h>
      int func (void) { return 1; }
      int main (void) {
        __returns_int;
        __checked_call(0 == func(),
          printf(\"executed\\n\");
        );
        return 0;
      }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -DDEBUG -lgrapes"
  then it should return 0
  when I run
  then I should see "a.out:<stdin>:9: error: checked call failed: 0 == func()"
  and I should see "executed"
  and it should not return 0

### test the min / max macros
# test the min macro
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int main (void) {
      int x = min(3, 9);
      int y = min(6, 6);
      int z = min(9, 3);
      float a = min(3.5, 9.5);
      printf(\"%u, %u, %u, %.2f\\n\", x, y, z, a);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should see "3, 6, 3, 3.50"
  and it should return 0
# test the max macro
given the c code "
    #include <grapes/util.h>
    #include <stdio.h>
    int main (void) {
      int x = max(3, 9);
      int y = max(6, 6);
      int z = max(9, 3);
      float a = max(3.5, 9.5);
      printf(\"%u, %u, %u, %.2f\\n\", x, y, z, a);
      return 0;
    }"
  when I compile with cflags "-I${incdir} -L${libdir} -Wall -Wextra -Werror -lgrapes"
  then it should return 0
  when I run
  then I should see "9, 6, 9, 9.50"
  and it should return 0

send_user "\n"
